language: python
python:
  - 3.7
  - 3.8
install:
  - pip install flake8

before_script:
  - flake8 --version
script:
  - flake8 --ignore=E123,E501,E502 --exclude=avanza/constants.py

notifications:
  email:
    on_success: never
    on_failure: change
